// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqWFVJ98T5_cKAoGHGEVF3N8nl1F8471Y',
    appId: '1:325116512963:web:850248b0dfe700bfc07076',
    messagingSenderId: '325116512963',
    projectId: 'socialmedia-b0e36',
    authDomain: 'socialmedia-b0e36.firebaseapp.com',
    storageBucket: 'socialmedia-b0e36.appspot.com',
    measurementId: 'G-CEPXY4EGLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUEGWlpbFAOLOci23mwnXSOhIB3yzcF-s',
    appId: '1:325116512963:android:9307e685ae8f4678c07076',
    messagingSenderId: '325116512963',
    projectId: 'socialmedia-b0e36',
    storageBucket: 'socialmedia-b0e36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0jm3CVPYvlsxbJmmlXtQSZ8OkzOKeZA',
    appId: '1:325116512963:ios:ed4a3213e0303ad0c07076',
    messagingSenderId: '325116512963',
    projectId: 'socialmedia-b0e36',
    storageBucket: 'socialmedia-b0e36.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );
}
